server:
    port: 5000

spring:
    data:
        mongodb:
            uri: mongodb://ariasmj:Ariasmj2024$@localhost:27017/bankingAccount?authSource=admin # mongodb server address

kafka:
    bootstrap-servers: localhost:9092 # kafka server address
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer # key serializer class
        value-serializer: com.banking.account.cmd.infrastructure.EventSerializer # value serializer class