server:
  port: 5001
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankingAccount?createDatabaseIfNotExist=true
    username: ariasmj
    password: ariasmj2024
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: com.banking.account.query.infrastructure.EventDeserializer
        spring.json.trusted.packages: '*'
